name: Saved Search Digest (Weekly)

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  run-weekly-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Call weekly digest endpoint
        run: |
          curl -sS -X GET "$BASE_URL/api/cron/saved-search-digest?period=weekly" -H "X-CRON-KEY: $CRON_SECRET"
        env:
          BASE_URL: ${{ secrets.APP_BASE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}


